
[tool.poetry]
name = "video-helper"
version = "0.1.0"
description = "Video Helper is a Python library that provides utility functions for processing video files. It includes features like loading, converting, extracting frames as well as working with subtitle formats."
authors = ['Warith Harchaoui <warith.harchaoui@gmail.com>', 'Mohamed Chelali <mohamed.t.chelali@gmail.com>', 'Bachir Zerroug <bzerroug@gmail.com>']
license = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
    build = "1.2.2.post1"
    CacheControl = "0.14.0"
    certifi = "2024.8.30"
    cffi = "1.17.1"
    charset-normalizer = "3.4.0"
    cleo = "2.1.0"
    colorlog = "6.8.2"
    crashtest = "0.4.1"
    Cython = "3.0.11"
    distlib = "0.3.9"
    dulwich = "0.21.7"
    fastjsonschema = "2.20.0"
    ffmpeg-python = "0.2.0"
    filelock = "3.16.1"
    future = "1.0.0"
    idna = "3.10"
    importlib_metadata = "8.5.0"
    installer = "0.7.0"
    keyring = "24.3.1"
    more-itertools = "10.5.0"
    msgpack = "1.1.0"
    numpy = "2.0.2"
    opencv-python = "4.10.0.84"
    os-helper = { git = "https://github.com/warith-harchaoui/os-helper.git", branch = "main" }
    packaging = "24.1"
    pandas = "2.2.3"
    pexpect = "4.9.0"
    pkginfo = "1.11.2"
    platformdirs = "4.3.6"
    poetry = "1.8.4"
    poetry-core = "1.9.1"
    poetry-plugin-export = "1.8.0"
    poetry2setup = "1.1.0"
    ptyprocess = "0.7.0"
    pycparser = "2.22"
    pyproject_hooks = "1.2.0"
    python-dateutil = "2.9.0.post0"
    python-dotenv = "1.0.1"
    pytz = "2024.2"
    PyYAML = "6.0.2"
    RapidFuzz = "3.10.1"
    requests = "2.32.3"
    requests-toolbelt = "1.0.0"
    shellingham = "1.5.4"
    six = "1.16.0"
    tomli = "2.0.2"
    tomlkit = "0.13.2"
    tqdm = "4.66.6"
    trove-classifiers = "2024.10.21.16"
    tzdata = "2024.2"
    urllib3 = "2.2.3"
    validators = "0.34.0"
    vidgear = "0.3.3"
    virtualenv = "20.27.0"
    xattr = "1.1.0"
    zipp = "3.20.2"


[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
