"""
Functional tests for ``extract_frames``: backend dispatch, decode, and
destination/layout conversion.

Each test drives a full scenario (dispatch rule -> real decode -> output
contract) rather than asserting one branch in isolation, so the file's size
tracks the number of *behaviors* protected, not the number of parameter
combinations. Backend-specific tests skip cleanly when that backend isn't
installed on the current machine.
"""

from __future__ import annotations

import numpy as np
import os_helper as osh
import pytest

from video_helper import (
    black_video,
    extract_frames,
    is_valid_video_file,
)
from video_helper.main import (
    _BACKENDS,
    _choose_backend,
    _have_pyav,
    _resolve_hwaccel,
    _resolve_indices,
)

osh.verbosity(0)


# ---------------------------------------------------------------------------
# Fixture: a small reusable test clip generated by black_video.
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def clip(tmp_path_factory) -> str:
    """A 3-second 64x64 H.264 clip with 30 fps."""
    p = tmp_path_factory.mktemp("clip") / "test.mp4"
    black_video(3.0, 64, 64, str(p), frame_rate=30)
    assert is_valid_video_file(str(p))
    return str(p)


def _check_bgr_uint8(frame, width=64, height=64) -> None:
    """Assert a frame is a BGR uint8 ndarray of the expected (H, W, 3) shape."""
    assert isinstance(frame, np.ndarray)
    assert frame.dtype == np.uint8
    assert frame.shape == (height, width, 3)


# ---------------------------------------------------------------------------
# Internal resolvers: pure logic, no I/O, no fixtures needed.
# ---------------------------------------------------------------------------


def test_internal_resolvers_pure_logic() -> None:
    """``_resolve_hwaccel``, ``_choose_backend``, and ``_resolve_indices`` are
    pure dispatch/arithmetic helpers -- exercised together since none needs
    I/O and all three gate the same ``extract_frames`` call."""
    # _resolve_hwaccel: explicit passthrough, and 'auto' never returns garbage.
    assert _resolve_hwaccel(None) is None
    assert _resolve_hwaccel("cuda") == "cuda"
    assert _resolve_hwaccel("videotoolbox") == "videotoolbox"
    assert _resolve_hwaccel("auto") in {None, "videotoolbox", "cuda", "qsv"}

    # _choose_backend: explicit dispatch rules.
    assert _choose_backend("auto", stabilize=True, sparse=False, full_sequential=False) == "vidgear"
    with pytest.raises(ValueError):
        _choose_backend("pyav", stabilize=True, sparse=False, full_sequential=False)
    with pytest.raises(ValueError):
        _choose_backend("bogus", stabilize=False, sparse=False, full_sequential=False)
    with pytest.raises(ValueError):
        _choose_backend(
            "decord", stabilize=False, sparse=False, full_sequential=False
        )  # removed in v1.4.0
    for b in _BACKENDS:
        if b != "auto":
            assert _choose_backend(b, stabilize=False, sparse=False, full_sequential=False) == b

    # _choose_backend: 'auto' heuristics (sparse/full-sequential/windowed).
    sparse_pick = _choose_backend("auto", stabilize=False, sparse=True, full_sequential=False)
    full_seq_pick = _choose_backend("auto", stabilize=False, sparse=False, full_sequential=True)
    windowed_pick = _choose_backend("auto", stabilize=False, sparse=False, full_sequential=False)
    assert full_seq_pick == "vidgear"  # 4x faster on macOS for full sequential decode
    if _have_pyav():
        assert sparse_pick == "pyav"
        assert windowed_pick == "pyav"  # keyframe seek beats vidgear's decode-from-t0
    else:
        assert sparse_pick == "vidgear"
        assert windowed_pick in {"ffmpeg-pipe", "vidgear"}

    # _resolve_indices: sparse mode (from times, and out-of-range clipping).
    indices, *_, sparse = _resolve_indices(
        duration=2.0,
        frame_rate=30.0,
        start_index=None,
        end_index=None,
        start_instant=None,
        end_instant=None,
        frame_step=1,
        frame_interval=None,
        frame_indices=None,
        frame_times=[0.0, 1.0, 1.5],
    )
    assert sparse is True
    assert indices == [0, 30, 45]

    clipped, *_ = _resolve_indices(
        duration=1.0,
        frame_rate=30.0,
        start_index=None,
        end_index=None,
        start_instant=None,
        end_instant=None,
        frame_step=1,
        frame_interval=None,
        frame_indices=[-5, 0, 10, 999],
        frame_times=None,
    )
    assert clipped == [0, 10]  # negatives and out-of-bounds dropped

    # _resolve_indices: range mode (seconds -> frame index range + step).
    _, s, e, step, range_sparse = _resolve_indices(
        duration=10.0,
        frame_rate=30.0,
        start_index=None,
        end_index=None,
        start_instant=1.0,
        end_instant=2.0,
        frame_step=1,
        frame_interval=0.1,
        frame_indices=None,
        frame_times=None,
    )
    assert range_sparse is False
    assert (s, e, step) == (30, 60, 3)  # 0.1s @ 30fps -> step 3

    with pytest.raises(AssertionError):
        _resolve_indices(
            duration=1.0,
            frame_rate=30.0,
            start_index=20,
            end_index=5,
            start_instant=None,
            end_instant=None,
            frame_step=1,
            frame_interval=None,
            frame_indices=None,
            frame_times=None,
        )


# ---------------------------------------------------------------------------
# End-to-end: per-backend decode + cross-backend equivalence.
# ---------------------------------------------------------------------------


def test_sequential_backends_yield_bgr_uint8(clip) -> None:
    """Every installed backend, driven explicitly, yields BGR uint8 frames
    over the same sequential window (also covers ``hwaccel='auto'`` not
    breaking decode when forwarded to a backend that doesn't support it)."""
    backends = ["vidgear", "ffmpeg-pipe"]
    if _have_pyav():
        backends.append("pyav")
    for backend in backends:
        frames = list(
            extract_frames(
                clip,
                start_instant=0.5,
                end_instant=1.5,
                frame_step=5,
                backend=backend,
                hwaccel="auto" if backend == "pyav" else None,
            )
        )
        assert len(frames) > 0, backend
        for f in frames:
            _check_bgr_uint8(f)


@pytest.mark.skipif(not _have_pyav(), reason="PyAV not installed")
def test_pyav_backend_sparse(clip) -> None:
    """The PyAV backend yields one frame per requested sparse frame_time."""
    frames = list(extract_frames(clip, frame_times=[0.1, 1.0, 2.0], backend="pyav", hwaccel=None))
    assert len(frames) == 3
    for f in frames:
        _check_bgr_uint8(f)


@pytest.mark.skipif(not _have_pyav(), reason="PyAV not installed")
def test_pyav_vs_vidgear_count_matches(clip) -> None:
    """Same range/step should yield the same number of frames across backends."""
    vid = list(
        extract_frames(
            clip, start_instant=0.0, end_instant=1.0, frame_step=10, backend="vidgear", hwaccel=None
        )
    )
    pyav = list(
        extract_frames(
            clip, start_instant=0.0, end_instant=1.0, frame_step=10, backend="pyav", hwaccel=None
        )
    )
    # Allow +/-1 frame for keyframe-boundary differences between backends.
    assert abs(len(vid) - len(pyav)) <= 1


def test_backward_compat_default_backend(clip) -> None:
    """Omitting backend/hwaccel (old call signature) keeps working and yields
    the same (H, W, 3) BGR uint8 contract as an explicit call."""
    frames = list(extract_frames(clip, start_instant=0.0, end_instant=1.0, frame_step=5))
    assert len(frames) > 0
    for f in frames:
        _check_bgr_uint8(f)


# ---------------------------------------------------------------------------
# destination= / batch_size= / layout= (v1.4.0) and input validation.
# ---------------------------------------------------------------------------


def _have_torch() -> bool:
    """Return True if PyTorch is importable in the current environment."""
    try:
        import torch  # noqa: F401

        return True
    except ImportError:
        return False


def _have_pil() -> bool:
    """Return True if Pillow is importable in the current environment."""
    try:
        import PIL.Image  # noqa: F401

        return True
    except ImportError:
        return False


def test_numpy_destination_batched(clip) -> None:
    """batch_size with numpy destination yields (N,H,W,3) ndarrays whose total
    frame count matches the unbatched call."""
    batches = list(
        extract_frames(
            clip,
            start_instant=0.0,
            end_instant=1.0,
            frame_step=5,
            destination="numpy",
            batch_size=3,
        )
    )
    assert len(batches) > 0
    total_frames = 0
    for b in batches:
        assert isinstance(b, np.ndarray)
        assert b.ndim == 4 and b.shape[1:] == (64, 64, 3)
        assert b.shape[0] <= 3  # last batch may be smaller
        total_frames += b.shape[0]
    unbatched = list(extract_frames(clip, start_instant=0.0, end_instant=1.0, frame_step=5))
    assert total_frames == len(unbatched)


def test_extract_frames_rejects_invalid_options(clip) -> None:
    """Every input-validation error path raises the documented ValueError,
    naming the offending option -- covers destination/layout/batch_size
    validation plus the ffmpeg-pipe backend's sparse-mode restriction."""
    with pytest.raises(ValueError, match="destination"):
        list(extract_frames(clip, start_instant=0.0, end_instant=0.2, destination="bogus"))
    with pytest.raises(ValueError, match="layout"):
        list(
            extract_frames(
                clip,
                start_instant=0.0,
                end_instant=0.2,
                destination="numpy",
                batch_size=2,
                layout="bogus",
            )
        )
    with pytest.raises(ValueError, match="batch_size"):
        list(
            extract_frames(
                clip, start_instant=0.0, end_instant=0.2, destination="numpy", batch_size=0
            )
        )
    with pytest.raises(ValueError, match="sparse"):
        list(extract_frames(clip, frame_times=[0.5, 1.0], backend="ffmpeg-pipe", hwaccel=None))


def test_destination_raises_clear_importerror_when_optional_dep_absent(clip) -> None:
    """destination='torch'/'pil' raise a clear ImportError naming the missing
    package when that optional dependency is not installed -- opportunistic,
    since both are installed in this dev environment."""
    if not _have_torch():
        with pytest.raises(ImportError, match="torch"):
            list(extract_frames(clip, start_instant=0.0, end_instant=0.2, destination="torch"))
    if not _have_pil():
        with pytest.raises(ImportError, match="Pillow"):
            list(extract_frames(clip, start_instant=0.0, end_instant=0.2, destination="pil"))
    if _have_torch() and _have_pil():
        pytest.skip("torch and Pillow are both installed; can't simulate absence")


@pytest.mark.skipif(not _have_torch(), reason="torch not installed")
def test_torch_destination_unbatched_chw_rgb_and_channel_flip(clip) -> None:
    """Unbatched torch yields CHW RGB uint8 (PyTorch convention), and the
    BGR->RGB channel flip actually happened (checked pixel-for-pixel against
    the numpy/BGR output of the same frame)."""
    import torch

    frames = list(
        extract_frames(clip, start_instant=0.0, end_instant=0.5, destination="torch", device="cpu")
    )
    assert len(frames) > 0
    for t in frames:
        assert isinstance(t, torch.Tensor)
        assert t.dtype == torch.uint8
        assert tuple(t.shape) == (3, 64, 64)  # CHW, not HWC
        assert t.device.type == "cpu"

    np_frame = next(iter(extract_frames(clip, frame_indices=[0])))  # (H,W,3) BGR
    th_frame = next(
        iter(extract_frames(clip, frame_indices=[0], destination="torch", device="cpu"))
    )  # (3,H,W) RGB
    np_pixel = np_frame[0, 0]  # [B, G, R]
    th_pixel = th_frame[:, 0, 0]  # [R, G, B]
    assert int(np_pixel[0]) == int(th_pixel[2])  # B
    assert int(np_pixel[1]) == int(th_pixel[1])  # G
    assert int(np_pixel[2]) == int(th_pixel[0])  # R


@pytest.mark.skipif(not _have_torch(), reason="torch not installed")
def test_torch_destination_batched_layouts(clip) -> None:
    """layout='image' yields NCHW (batch-of-images); layout='video' yields
    CTHW (video clip); device='auto' resolves to a real torch device.
    Frame-count totals match the unbatched call in both layouts."""
    import torch

    unbatched = list(extract_frames(clip, start_instant=0.0, end_instant=1.0, frame_step=5))

    image_batches = list(
        extract_frames(
            clip,
            start_instant=0.0,
            end_instant=1.0,
            frame_step=5,
            destination="torch",
            device="auto",
            batch_size=4,
            layout="image",
        )
    )
    assert len(image_batches) > 0
    total = 0
    for b in image_batches:
        assert isinstance(b, torch.Tensor)
        assert b.ndim == 4 and b.shape[1] == 3 and tuple(b.shape[2:]) == (64, 64)  # NCHW
        assert b.shape[0] <= 4
        assert b.device.type in {"cpu", "mps", "cuda"}
        total += b.shape[0]
    assert total == len(unbatched)

    video_batches = list(
        extract_frames(
            clip,
            start_instant=0.0,
            end_instant=1.0,
            frame_step=5,
            destination="torch",
            device="cpu",
            batch_size=4,
            layout="video",
        )
    )
    assert len(video_batches) > 0
    total_T = 0
    for b in video_batches:
        assert b.ndim == 4 and b.shape[0] == 3 and tuple(b.shape[2:]) == (64, 64)  # CTHW
        assert b.shape[1] <= 4
        total_T += b.shape[1]
    assert total_T == len(unbatched)


@pytest.mark.skipif(
    not _have_torch()
    or not (
        hasattr(__import__("torch").backends, "mps")
        and __import__("torch").backends.mps.is_available()
    ),
    reason="torch + MPS required",
)
def test_torch_destination_mps_image_batched(clip) -> None:
    """On Apple Silicon: NCHW tensors land on MPS."""
    batches = list(
        extract_frames(
            clip,
            start_instant=0.0,
            end_instant=1.0,
            destination="torch",
            device="mps",
            batch_size=8,
            layout="image",
        )
    )
    assert len(batches) > 0
    for b in batches:
        assert b.device.type == "mps"
        assert b.shape[1] == 3  # NCHW


@pytest.mark.skipif(not _have_pil(), reason="Pillow not installed")
def test_pil_destination_yields_rgb_images_and_rejects_batch_size(clip) -> None:
    """PIL: yields PIL.Image (RGB mode, size=(W, H)), and batch_size is
    rejected since PIL images are yielded one at a time."""
    from PIL import Image

    frames = list(extract_frames(clip, start_instant=0.0, end_instant=0.3, destination="pil"))
    assert len(frames) > 0
    for im in frames:
        assert isinstance(im, Image.Image)
        assert im.mode == "RGB"
        assert im.size == (64, 64)  # PIL.size is (width, height)

    with pytest.raises(ValueError, match="batch_size"):
        list(
            extract_frames(
                clip, start_instant=0.0, end_instant=0.2, destination="pil", batch_size=4
            )
        )
