"""
Backend dispatch tests for ``extract_frames``.

Each test that targets a specific backend skips when that backend isn't
installed on the current machine. The dispatcher tests use mocking to
exercise the routing logic without depending on installed packages.
"""

from __future__ import annotations

import numpy as np
import os_helper as osh
import pytest

from video_helper import (
    black_video,
    extract_frames,
    is_valid_video_file,
    video_dimensions,
)
from video_helper.main import (
    _BACKENDS,
    _choose_backend,
    _have_pyav,
    _resolve_hwaccel,
    _resolve_indices,
)

osh.verbosity(0)


# ---------------------------------------------------------------------------
# Fixture: a small reusable test clip generated by black_video.
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def clip(tmp_path_factory):
    """A 3-second 64x64 H.264 clip with 30 fps."""
    p = tmp_path_factory.mktemp("clip") / "test.mp4"
    black_video(3.0, 64, 64, str(p), frame_rate=30)
    assert is_valid_video_file(str(p))
    return str(p)


# ---------------------------------------------------------------------------
# _resolve_hwaccel
# ---------------------------------------------------------------------------


def test_resolve_hwaccel_explicit_passthrough():
    assert _resolve_hwaccel(None) is None
    assert _resolve_hwaccel("cuda") == "cuda"
    assert _resolve_hwaccel("videotoolbox") == "videotoolbox"


def test_resolve_hwaccel_auto_returns_known_or_none():
    """`auto` returns either a string ffmpeg knows about, or None — never garbage."""
    val = _resolve_hwaccel("auto")
    assert val in {None, "videotoolbox", "cuda", "qsv"}


# ---------------------------------------------------------------------------
# _choose_backend
# ---------------------------------------------------------------------------


def test_choose_backend_stabilize_forces_vidgear():
    assert _choose_backend("auto", stabilize=True, sparse=False, full_sequential=False) == "vidgear"
    # Even when explicit, stabilize + non-vidgear must raise.
    with pytest.raises(ValueError):
        _choose_backend("pyav", stabilize=True, sparse=False, full_sequential=False)


def test_choose_backend_rejects_unknown():
    with pytest.raises(ValueError):
        _choose_backend("bogus", stabilize=False, sparse=False, full_sequential=False)


def test_choose_backend_rejects_decord_after_removal():
    """decord was dropped in v1.4.0 — passing it must raise."""
    with pytest.raises(ValueError):
        _choose_backend("decord", stabilize=False, sparse=False, full_sequential=False)


def test_choose_backend_explicit_passthrough():
    for b in _BACKENDS:
        if b == "auto":
            continue
        assert _choose_backend(b, stabilize=False, sparse=False, full_sequential=False) == b


def test_choose_backend_auto_sparse_prefers_pyav():
    chosen = _choose_backend("auto", stabilize=False, sparse=True, full_sequential=False)
    if _have_pyav():
        assert chosen == "pyav"
    else:
        assert chosen == "vidgear"


def test_choose_backend_auto_full_sequential_prefers_vidgear():
    """Full sequential (start=0, end=total, step=1) routes to VidGear (4x faster on macOS)."""
    assert _choose_backend("auto", stabilize=False, sparse=False, full_sequential=True) == "vidgear"


def test_choose_backend_auto_windowed_prefers_pyav():
    """Windowed sequential routes to PyAV (keyframe seek beats vidgear's decode-from-t0)."""
    chosen = _choose_backend("auto", stabilize=False, sparse=False, full_sequential=False)
    if _have_pyav():
        assert chosen == "pyav"
    else:
        assert chosen in {"ffmpeg-pipe", "vidgear"}


# ---------------------------------------------------------------------------
# _resolve_indices
# ---------------------------------------------------------------------------


def test_resolve_indices_sparse_from_times():
    indices, _, _, _, sparse = _resolve_indices(
        duration=2.0, frame_rate=30.0,
        start_index=None, end_index=None,
        start_instant=None, end_instant=None,
        frame_step=1, frame_interval=None,
        frame_indices=None, frame_times=[0.0, 1.0, 1.5],
    )
    assert sparse is True
    assert indices == [0, 30, 45]


def test_resolve_indices_sparse_clips_out_of_range():
    indices, *_ = _resolve_indices(
        duration=1.0, frame_rate=30.0,
        start_index=None, end_index=None,
        start_instant=None, end_instant=None,
        frame_step=1, frame_interval=None,
        frame_indices=[-5, 0, 10, 999], frame_times=None,
    )
    assert indices == [0, 10]  # negatives and out-of-bounds dropped


def test_resolve_indices_range_from_seconds():
    _, s, e, step, sparse = _resolve_indices(
        duration=10.0, frame_rate=30.0,
        start_index=None, end_index=None,
        start_instant=1.0, end_instant=2.0,
        frame_step=1, frame_interval=0.1,
        frame_indices=None, frame_times=None,
    )
    assert sparse is False
    assert s == 30 and e == 60
    assert step == 3  # 0.1s @ 30fps


def test_resolve_indices_rejects_inverted_range():
    with pytest.raises(AssertionError):
        _resolve_indices(
            duration=1.0, frame_rate=30.0,
            start_index=20, end_index=5,
            start_instant=None, end_instant=None,
            frame_step=1, frame_interval=None,
            frame_indices=None, frame_times=None,
        )


# ---------------------------------------------------------------------------
# End-to-end: per-backend
# ---------------------------------------------------------------------------


def _check_bgr_uint8(frame, width=64, height=64):
    assert isinstance(frame, np.ndarray)
    assert frame.dtype == np.uint8
    assert frame.shape == (height, width, 3)


def test_vidgear_backend_sequential(clip):
    frames = list(
        extract_frames(clip, start_instant=0.5, end_instant=1.5,
                       frame_step=5, backend="vidgear", hwaccel=None)
    )
    assert len(frames) > 0
    for f in frames:
        _check_bgr_uint8(f)


@pytest.mark.skipif(not _have_pyav(), reason="PyAV not installed")
def test_pyav_backend_sequential(clip):
    frames = list(
        extract_frames(clip, start_instant=0.5, end_instant=1.5,
                       frame_step=5, backend="pyav", hwaccel=None)
    )
    assert len(frames) > 0
    for f in frames:
        _check_bgr_uint8(f)


@pytest.mark.skipif(not _have_pyav(), reason="PyAV not installed")
def test_pyav_backend_sparse(clip):
    frames = list(
        extract_frames(clip, frame_times=[0.1, 1.0, 2.0],
                       backend="pyav", hwaccel=None)
    )
    assert len(frames) == 3
    for f in frames:
        _check_bgr_uint8(f)


@pytest.mark.skipif(not _have_pyav(), reason="PyAV not installed")
def test_pyav_backend_with_hwaccel_auto(clip):
    """`hwaccel='auto'` must not break PyAV decode (the value just gets
    forwarded to libav; if the host build doesn't support it, ffmpeg
    falls back to software decode silently)."""
    frames = list(
        extract_frames(clip, start_instant=0.0, end_instant=0.5,
                       backend="pyav", hwaccel="auto")
    )
    assert len(frames) > 0


def test_ffmpeg_pipe_backend_sequential(clip):
    frames = list(
        extract_frames(clip, start_instant=0.5, end_instant=1.5,
                       backend="ffmpeg-pipe", hwaccel=None)
    )
    assert len(frames) > 0
    for f in frames:
        _check_bgr_uint8(f)


def test_ffmpeg_pipe_backend_rejects_sparse(clip):
    with pytest.raises(ValueError, match="sparse"):
        list(extract_frames(clip, frame_times=[0.5, 1.0],
                            backend="ffmpeg-pipe", hwaccel=None))


# ---------------------------------------------------------------------------
# Cross-backend equivalence (when multiple backends are available)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not _have_pyav(), reason="PyAV not installed")
def test_pyav_vs_vidgear_count_matches(clip):
    """Same range/step should yield the same number of frames across backends."""
    vid = list(extract_frames(clip, start_instant=0.0, end_instant=1.0,
                              frame_step=10, backend="vidgear", hwaccel=None))
    pyav = list(extract_frames(clip, start_instant=0.0, end_instant=1.0,
                               frame_step=10, backend="pyav", hwaccel=None))
    # Allow ±1 frame for keyframe-boundary differences between backends.
    assert abs(len(vid) - len(pyav)) <= 1


# ---------------------------------------------------------------------------
# Backward compatibility with the old call signature
# ---------------------------------------------------------------------------


def test_backward_compat_old_signature(clip):
    """Old positional/keyword form keeps working without explicit backend/hwaccel."""
    frames = list(extract_frames(clip, start_instant=0.0, end_instant=1.0, frame_step=5))
    assert len(frames) > 0
    for f in frames:
        _check_bgr_uint8(f)


# ---------------------------------------------------------------------------
# destination= and batch_size= (v1.4.0)
# ---------------------------------------------------------------------------


def _have_torch() -> bool:
    try:
        import torch  # noqa: F401
        return True
    except ImportError:
        return False


def test_numpy_destination_default_unchanged(clip):
    """The default destination must yield (H,W,3) BGR uint8 ndarrays — backward compat."""
    frames = list(extract_frames(clip, start_instant=0.0, end_instant=0.5))
    assert len(frames) > 0
    for f in frames:
        assert isinstance(f, np.ndarray)
        assert f.dtype == np.uint8
        assert f.shape == (64, 64, 3)


def test_numpy_destination_batched(clip):
    """batch_size with numpy destination yields (N,H,W,3) ndarrays."""
    batches = list(extract_frames(
        clip, start_instant=0.0, end_instant=1.0, frame_step=5,
        destination="numpy", batch_size=3,
    ))
    assert len(batches) > 0
    total_frames = 0
    for b in batches:
        assert isinstance(b, np.ndarray)
        assert b.ndim == 4 and b.shape[1:] == (64, 64, 3)
        assert b.shape[0] <= 3  # last batch may be smaller
        total_frames += b.shape[0]
    # Compare against unbatched count
    unbatched = list(extract_frames(
        clip, start_instant=0.0, end_instant=1.0, frame_step=5,
    ))
    assert total_frames == len(unbatched)


def test_destination_rejects_unknown(clip):
    with pytest.raises(ValueError, match="destination"):
        list(extract_frames(clip, start_instant=0.0, end_instant=0.2, destination="bogus"))


def test_destination_torch_raises_when_torch_absent(clip):
    if _have_torch():
        pytest.skip("torch is installed; can't simulate absence")
    with pytest.raises(ImportError, match="torch"):
        list(extract_frames(clip, start_instant=0.0, end_instant=0.2, destination="torch"))


def test_batch_size_rejects_zero(clip):
    with pytest.raises(ValueError, match="batch_size"):
        list(extract_frames(clip, start_instant=0.0, end_instant=0.2,
                            destination="numpy", batch_size=0))


@pytest.mark.skipif(not _have_torch(), reason="torch not installed")
def test_torch_destination_cpu_unbatched(clip):
    import torch
    frames = list(extract_frames(
        clip, start_instant=0.0, end_instant=0.5,
        destination="torch", device="cpu",
    ))
    assert len(frames) > 0
    for t in frames:
        assert isinstance(t, torch.Tensor)
        assert t.dtype == torch.uint8
        assert tuple(t.shape) == (64, 64, 3)
        assert t.device.type == "cpu"


@pytest.mark.skipif(not _have_torch(), reason="torch not installed")
def test_torch_destination_batched(clip):
    import torch
    batches = list(extract_frames(
        clip, start_instant=0.0, end_instant=1.0, frame_step=5,
        destination="torch", device="cpu", batch_size=4,
    ))
    assert len(batches) > 0
    total = 0
    for b in batches:
        assert isinstance(b, torch.Tensor)
        assert b.ndim == 4 and tuple(b.shape[1:]) == (64, 64, 3)
        assert b.shape[0] <= 4
        total += b.shape[0]
    unbatched = list(extract_frames(
        clip, start_instant=0.0, end_instant=1.0, frame_step=5,
    ))
    assert total == len(unbatched)


@pytest.mark.skipif(
    not _have_torch(),
    reason="torch not installed",
)
def test_torch_destination_auto_device_resolves(clip):
    """device='auto' must resolve to a real torch device."""
    import torch
    frames = list(extract_frames(
        clip, start_instant=0.0, end_instant=0.2,
        destination="torch", device="auto",
    ))
    assert len(frames) > 0
    # The device picked depends on the box (cuda > mps > cpu); just verify it's one of these.
    assert frames[0].device.type in {"cpu", "mps", "cuda"}


@pytest.mark.skipif(
    not _have_torch() or not (hasattr(__import__("torch").backends, "mps")
                              and __import__("torch").backends.mps.is_available()),
    reason="torch + MPS required",
)
def test_torch_destination_mps_batched(clip):
    """On Apple Silicon: tensors land on MPS, batched transfer is the right pattern."""
    import torch
    batches = list(extract_frames(
        clip, start_instant=0.0, end_instant=1.0,
        destination="torch", device="mps", batch_size=8,
    ))
    assert len(batches) > 0
    for b in batches:
        assert b.device.type == "mps"
        assert b.ndim == 4
